spring.application.name=tflcomentor
server.port=8081
spring.datasource.url=jdbc:mysql://192.168.1.149:3306/tflcomentor_db
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver