// <auto-generated />
using System;
using Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414064856_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.AcademicInformation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CollegeName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("college_name");

                    b.Property<long?>("EnrollmentYear")
                        .HasColumnType("bigint")
                        .HasColumnName("enrollment_year");

                    b.Property<long?>("PassingYear")
                        .HasColumnType("bigint")
                        .HasColumnName("passing_year");

                    b.Property<decimal?>("Percentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("percentage");

                    b.Property<string>("Specialization")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("specialization");

                    b.Property<string>("StreamName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("stream_name");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "user_id");

                    b.ToTable("academic_informations", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Alumnus", b =>
                {
                    b.Property<long>("AlumniId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("alumni_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("AlumniId"));

                    b.Property<DateTime?>("AddedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("added_at");

                    b.Property<long?>("CompaniesId")
                        .HasColumnType("bigint")
                        .HasColumnName("companies_id");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("AlumniId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CompaniesId" }, "companies_id");

                    b.HasIndex(new[] { "UserId" }, "user_id")
                        .HasDatabaseName("user_id1");

                    b.ToTable("alumni", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Assessment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("AssignedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("assigned_by");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("datetime")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Assigned','Pending','Completed')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Pending'");

                    b.Property<long?>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("student_id");

                    b.Property<long?>("TestId")
                        .HasColumnType("bigint")
                        .HasColumnName("test_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AssignedBy" }, "fk_assessment_assigned_by");

                    b.HasIndex(new[] { "StudentId" }, "fk_assessment_student");

                    b.HasIndex(new[] { "TestId" }, "fk_assessment_test");

                    b.ToTable("assessments", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Company", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("company_name");

                    b.Property<string>("CompanySize")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("company_size");

                    b.Property<string>("CompanyType")
                        .HasColumnType("enum('STARTUP','PRODUCT','SERVICE')")
                        .HasColumnName("company_type");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("industry");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Concept", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("concepts", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Framework", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<long?>("LanguageId")
                        .HasColumnType("bigint")
                        .HasColumnName("language_id");

                    b.Property<long?>("LayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("layer_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "LanguageId" }, "language_id");

                    b.HasIndex(new[] { "LayerId" }, "layer_id");

                    b.ToTable("frameworks", (string)null);
                });

            modelBuilder.Entity("Backend.Models.FrameworkConcept", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ConceptId")
                        .HasColumnType("bigint")
                        .HasColumnName("concept_id");

                    b.Property<long?>("FrameworkId")
                        .HasColumnType("bigint")
                        .HasColumnName("framework_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ConceptId" }, "concept_id");

                    b.HasIndex(new[] { "FrameworkId" }, "framework_id");

                    b.ToTable("framework_concepts", (string)null);
                });

            modelBuilder.Entity("Backend.Models.HandsOnResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("QuestionId")
                        .HasColumnType("bigint")
                        .HasColumnName("question_id");

                    b.Property<long?>("Score")
                        .HasColumnType("bigint")
                        .HasColumnName("score");

                    b.Property<long?>("SmeId")
                        .HasColumnType("bigint")
                        .HasColumnName("sme_id");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("status");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "QuestionId" }, "question_id");

                    b.HasIndex(new[] { "SmeId" }, "sme_id");

                    b.HasIndex(new[] { "UserId" }, "user_id")
                        .HasDatabaseName("user_id2");

                    b.ToTable("hands_on_results", (string)null);
                });

            modelBuilder.Entity("Backend.Models.HandsOnSubmission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("GithubLink")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("github_link");

                    b.Property<long?>("QuestionId")
                        .HasColumnType("bigint")
                        .HasColumnName("question_id");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("submitted_at");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "QuestionId" }, "question_id")
                        .HasDatabaseName("question_id1");

                    b.HasIndex(new[] { "UserId" }, "user_id")
                        .HasDatabaseName("user_id3");

                    b.ToTable("hands_on_submissions", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Interview", b =>
                {
                    b.Property<long>("InterviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("interview_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("InterviewId"));

                    b.Property<long?>("ApplicationId")
                        .HasColumnType("bigint")
                        .HasColumnName("application_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Mode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("mode");

                    b.Property<string>("Outcome")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("outcome");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark");

                    b.Property<DateTime?>("RescheduledAt")
                        .HasColumnType("datetime")
                        .HasColumnName("rescheduled_at");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("datetime")
                        .HasColumnName("scheduled_at");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("status");

                    b.HasKey("InterviewId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ApplicationId" }, "fk_interview_application");

                    b.ToTable("interviews", (string)null);
                });

            modelBuilder.Entity("Backend.Models.JobApplication", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AppliedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("applied_at");

                    b.Property<long?>("JobId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_id");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("status");

                    b.Property<long?>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("student_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "JobId" }, "fk_app_job");

                    b.HasIndex(new[] { "StudentId" }, "fk_app_student");

                    b.ToTable("job_applications", (string)null);
                });

            modelBuilder.Entity("Backend.Models.JobDescription", b =>
                {
                    b.Property<long>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("job_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("JobId"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long?>("EmployerId")
                        .HasColumnType("bigint")
                        .HasColumnName("employer_id");

                    b.Property<string>("JobType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("job_type");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("location");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("JobId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "EmployerId" }, "fk_job_employer");

                    b.ToTable("job_descriptions", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Language", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Language1")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("language");

                    b.Property<long?>("RuntimeId")
                        .HasColumnType("bigint")
                        .HasColumnName("runtime_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RuntimeId" }, "runtime_id");

                    b.ToTable("languages", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Layer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Layers")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("layers");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("layers", (string)null);
                });

            modelBuilder.Entity("Backend.Models.LearningPath", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<long?>("MentorId")
                        .HasColumnType("bigint")
                        .HasColumnName("mentor_id");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.Property<int?>("TotalModules")
                        .HasColumnType("int")
                        .HasColumnName("total_modules");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MentorId" }, "fk_learningpath_mentor");

                    b.ToTable("learning_paths", (string)null);
                });

            modelBuilder.Entity("Backend.Models.LearningPathProgress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AveragePercentage")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("average_percentage");

                    b.Property<decimal?>("ImprovementRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("improvement_rate");

                    b.Property<long?>("LearningPathId")
                        .HasColumnType("bigint")
                        .HasColumnName("learning_path_id");

                    b.Property<int?>("MaxScore")
                        .HasColumnType("int")
                        .HasColumnName("max_score");

                    b.Property<int?>("MinScore")
                        .HasColumnType("int")
                        .HasColumnName("min_score");

                    b.Property<decimal?>("OverallScore")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("overall_score");

                    b.Property<long?>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "LearningPathId" }, "fk_progress_path");

                    b.HasIndex(new[] { "StudentId", "LearningPathId" }, "student_id")
                        .IsUnique();

                    b.ToTable("learning_path_progress", (string)null);
                });

            modelBuilder.Entity("Backend.Models.LearningResource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ResourceUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("resource_url");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('ACTIVE','INACTIVE','ARCHIVED')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'ACTIVE'");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .HasColumnType("enum('VIDEO','DOC','LINK')")
                        .HasColumnName("type");

                    b.Property<long?>("UploadedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UploadedBy" }, "fk_resource_user");

                    b.ToTable("learning_resources", (string)null);
                });

            modelBuilder.Entity("Backend.Models.McqOption", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CorrectAnswer")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("correct_answer");

                    b.Property<string>("OptionA")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("option_a");

                    b.Property<string>("OptionB")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("option_b");

                    b.Property<string>("OptionC")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("option_c");

                    b.Property<string>("OptionD")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("option_d");

                    b.Property<long?>("QuestionId")
                        .HasColumnType("bigint")
                        .HasColumnName("question_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "QuestionId" }, "question_id")
                        .HasDatabaseName("question_id2");

                    b.ToTable("mcq_options", (string)null);
                });

            modelBuilder.Entity("Backend.Models.MentorAppointment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Agenda")
                        .HasColumnType("text")
                        .HasColumnName("agenda");

                    b.Property<DateOnly?>("AppointmentDate")
                        .HasColumnType("date")
                        .HasColumnName("appointment_date");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("MeetingLink")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("meeting_link");

                    b.Property<long?>("MentorId")
                        .HasColumnType("bigint")
                        .HasColumnName("mentor_id");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('SCHEDULED','CANCELLED','COMPLETED')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'SCHEDULED'");

                    b.Property<long?>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("student_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MentorId" }, "fk_appointment_mentor");

                    b.HasIndex(new[] { "StudentId" }, "fk_appointment_student");

                    b.ToTable("mentor_appointments", (string)null);
                });

            modelBuilder.Entity("Backend.Models.MentorCounseling", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CounselingDate")
                        .HasColumnType("datetime")
                        .HasColumnName("counseling_date");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("MeetingLink")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("meeting_link");

                    b.Property<long?>("MenteeId")
                        .HasColumnType("bigint")
                        .HasColumnName("mentee_id");

                    b.Property<long?>("MentorId")
                        .HasColumnType("bigint")
                        .HasColumnName("mentor_id");

                    b.Property<string>("Remark")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("remark");

                    b.Property<string>("Subject")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("subject");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MenteeId" }, "fk_counseling_mentee");

                    b.HasIndex(new[] { "MentorId" }, "fk_counseling_mentor");

                    b.ToTable("mentor_counselings", (string)null);
                });

            modelBuilder.Entity("Backend.Models.MentorFeedback", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<long?>("MentorId")
                        .HasColumnType("bigint")
                        .HasColumnName("mentor_id");

                    b.Property<int?>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<string>("ReviewText")
                        .HasColumnType("text")
                        .HasColumnName("review_text");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("status");

                    b.Property<long?>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MentorId" }, "fk_feedback_mentor");

                    b.HasIndex(new[] { "StudentId" }, "fk_feedback_student");

                    b.ToTable("mentor_feedbacks", (string)null);
                });

            modelBuilder.Entity("Backend.Models.MentorMentee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("AssignedOn")
                        .HasColumnType("date")
                        .HasColumnName("assigned_on");

                    b.Property<long?>("MenteeId")
                        .HasColumnType("bigint")
                        .HasColumnName("mentee_id");

                    b.Property<long?>("MentorId")
                        .HasColumnType("bigint")
                        .HasColumnName("mentor_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MenteeId" }, "mentee_id");

                    b.HasIndex(new[] { "MentorId" }, "mentor_id");

                    b.ToTable("mentor_mentees", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<long?>("NotificationCategoriesId")
                        .HasColumnType("bigint")
                        .HasColumnName("notification_categories_id");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "NotificationCategoriesId" }, "fk_notification_category");

                    b.HasIndex(new[] { "UserId" }, "fk_notification_user");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Backend.Models.NotificationCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Category" }, "category")
                        .IsUnique();

                    b.ToTable("notification_categories", (string)null);
                });

            modelBuilder.Entity("Backend.Models.OralAssessment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ConceptId")
                        .HasColumnType("bigint")
                        .HasColumnName("concept_id");

                    b.Property<long?>("SmeId")
                        .HasColumnType("bigint")
                        .HasColumnName("sme_id");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('PENDING','IN_PROGRESS','COMPLETED')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'PENDING'");

                    b.Property<long?>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("student_id");

                    b.Property<DateTime?>("TimeScheduleAt")
                        .HasColumnType("datetime")
                        .HasColumnName("time_schedule_at");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ConceptId" }, "fk_oa_concept");

                    b.HasIndex(new[] { "SmeId" }, "fk_oa_sme");

                    b.HasIndex(new[] { "StudentId" }, "fk_oa_student");

                    b.ToTable("oral_assessments", (string)null);
                });

            modelBuilder.Entity("Backend.Models.OralQuestionAnswer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Answer")
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<string>("Questions")
                        .HasColumnType("text")
                        .HasColumnName("questions");

                    b.Property<string>("Rating")
                        .HasColumnType("enum('POOR','AVERAGE','GOOD','VERY_GOOD','EXCELLENT')")
                        .HasColumnName("rating");

                    b.Property<string>("Remark")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("remark");

                    b.Property<long?>("SmeId")
                        .HasColumnType("bigint")
                        .HasColumnName("sme_id");

                    b.Property<long?>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SmeId" }, "fk_oqa_sme");

                    b.HasIndex(new[] { "StudentId" }, "fk_oqa_student");

                    b.ToTable("oral_question_answers", (string)null);
                });

            modelBuilder.Entity("Backend.Models.PerformanceSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("PerformanceJson")
                        .HasColumnType("json")
                        .HasColumnName("performance_json");

                    b.Property<DateOnly?>("SnapshotDate")
                        .HasColumnType("date")
                        .HasColumnName("snapshot_date");

                    b.Property<long?>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "StudentId", "SnapshotDate" }, "student_id")
                        .IsUnique()
                        .HasDatabaseName("student_id1");

                    b.ToTable("performance_snapshots", (string)null);
                });

            modelBuilder.Entity("Backend.Models.PersonalInformation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("FullName")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("full_name")
                        .HasComputedColumnSql("concat(`first_name`,_utf8mb4' ',`last_name`)", true);

                    b.Property<string>("Gender")
                        .HasColumnType("enum('MALE','FEMALE')")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Pincode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("pincode");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "user_id")
                        .HasDatabaseName("user_id4");

                    b.ToTable("personal_informations", (string)null);
                });

            modelBuilder.Entity("Backend.Models.ProblemStatementAnswer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Answer")
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<long?>("QuestionId")
                        .HasColumnType("bigint")
                        .HasColumnName("question_id");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("submitted_at");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "QuestionId" }, "fk_psa_question");

                    b.ToTable("problem_statement_answers", (string)null);
                });

            modelBuilder.Entity("Backend.Models.ProfessionalInformation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("company_name");

                    b.Property<string>("EmploymentType")
                        .HasColumnType("enum('FULL_TIME','PART_TIME','INTERNSHIP')")
                        .HasColumnName("employment_type");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<long?>("ExperienceYears")
                        .HasColumnType("bigint")
                        .HasColumnName("experience_years");

                    b.Property<bool?>("IsCurrentJob")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_current_job");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("job_title");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("location");

                    b.Property<string>("Skills")
                        .HasColumnType("text")
                        .HasColumnName("skills");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "user_id")
                        .HasDatabaseName("user_id5");

                    b.ToTable("professional_informations", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Project", b =>
                {
                    b.Property<long>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("ProjectId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long?>("MentorId")
                        .HasColumnType("bigint")
                        .HasColumnName("mentor_id");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("project_name");

                    b.Property<string>("RepositoryUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("repository_url");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('IN_PROGRESS','PENDING','COMPLETED')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'PENDING'");

                    b.HasKey("ProjectId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "MentorId" }, "fk_project_mentor");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Backend.Models.ProjectMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("JoinedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("joined_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<long?>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ProjectId" }, "fk_pm_project");

                    b.HasIndex(new[] { "StudentId" }, "fk_pm_student");

                    b.ToTable("project_members", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Question", b =>
                {
                    b.Property<long>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("question_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("QuestionId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DifficultyLevel")
                        .HasColumnType("enum('BEGINNER','INTERMEDIATE','ADVANCE')")
                        .HasColumnName("difficulty_level");

                    b.Property<string>("QuestionType")
                        .HasColumnType("enum('MCQ','PROBLEM_STATEMENT','HANDS_ON')")
                        .HasColumnName("question_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('APPROVED','DRAFT','INACTIVE')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'DRAFT'");

                    b.HasKey("QuestionId")
                        .HasName("PRIMARY");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("Backend.Models.QuestionFrameworkConcept", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("FrameworkConceptsId")
                        .HasColumnType("bigint")
                        .HasColumnName("framework_concepts_id");

                    b.Property<long?>("QuestionId")
                        .HasColumnType("bigint")
                        .HasColumnName("question_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FrameworkConceptsId" }, "framework_concepts_id");

                    b.HasIndex(new[] { "QuestionId" }, "question_id")
                        .HasDatabaseName("question_id3");

                    b.ToTable("question_framework_concepts", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Referral", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AlumniId")
                        .HasColumnType("bigint")
                        .HasColumnName("alumni_id");

                    b.Property<long?>("CompaniesId")
                        .HasColumnType("bigint")
                        .HasColumnName("companies_id");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AlumniId" }, "alumni_id");

                    b.HasIndex(new[] { "CompaniesId" }, "companies_id")
                        .HasDatabaseName("companies_id1");

                    b.HasIndex(new[] { "UserId" }, "user_id")
                        .HasDatabaseName("user_id6");

                    b.ToTable("referrals", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Role", b =>
                {
                    b.Property<long>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("RoleId"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId")
                        .HasName("PRIMARY");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Runtime", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("RuntimeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("runtime_name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("runtimes", (string)null);
                });

            modelBuilder.Entity("Backend.Models.ShortlistedCandidate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("JobId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_id");

                    b.Property<string>("RoundLevel")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("round_level");

                    b.Property<DateTime?>("ShortlistedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("shortlisted_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "JobId" }, "fk_sc_job");

                    b.HasIndex(new[] { "UserId" }, "fk_sc_user");

                    b.ToTable("shortlisted_candidates", (string)null);
                });

            modelBuilder.Entity("Backend.Models.SmeRuntime", b =>
                {
                    b.Property<long>("SmeRuntimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sme_runtime_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SmeRuntimeId"));

                    b.Property<long?>("RuntimeId")
                        .HasColumnType("bigint")
                        .HasColumnName("runtime_id");

                    b.Property<long?>("UserRolesId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_roles_id");

                    b.HasKey("SmeRuntimeId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RuntimeId" }, "runtime_id")
                        .HasDatabaseName("runtime_id1");

                    b.HasIndex(new[] { "UserRolesId" }, "user_id")
                        .HasDatabaseName("user_id7");

                    b.ToTable("sme_runtimes", (string)null);
                });

            modelBuilder.Entity("Backend.Models.StudentAssessmentResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AssessmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("assessment_id");

                    b.Property<float?>("Percentile")
                        .HasColumnType("float")
                        .HasColumnName("percentile");

                    b.Property<float?>("Score")
                        .HasColumnType("float")
                        .HasColumnName("score");

                    b.Property<long?>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("student_id");

                    b.Property<long?>("TimeTakenMinutes")
                        .HasColumnType("bigint")
                        .HasColumnName("time_taken_minutes");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AssessmentId" }, "fk_result_assessment");

                    b.HasIndex(new[] { "StudentId" }, "fk_result_student");

                    b.ToTable("student_assessment_results", (string)null);
                });

            modelBuilder.Entity("Backend.Models.StudentConceptProgress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("completed_at");

                    b.Property<long?>("ConceptId")
                        .HasColumnType("bigint")
                        .HasColumnName("concept_id");

                    b.Property<DateTime?>("InitiatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("initiated_at");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('IN_PROGRESS','PENDING','COMPLETED')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'PENDING'");

                    b.Property<long?>("StudentId")
                        .HasColumnType("bigint")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ConceptId" }, "fk_scp_concept");

                    b.HasIndex(new[] { "StudentId" }, "fk_scp_student");

                    b.ToTable("student_concept_progress", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Test", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Difficulty")
                        .HasColumnType("enum('BEGINNER','INTERMEDIATE','ADVANCE')")
                        .HasColumnName("difficulty");

                    b.Property<long?>("Duration")
                        .HasColumnType("bigint")
                        .HasColumnName("duration");

                    b.Property<long?>("SmeRuntimeId")
                        .HasColumnType("bigint")
                        .HasColumnName("sme_runtime_id");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SmeRuntimeId" }, "fk_sme_runtime");

                    b.ToTable("tests", (string)null);
                });

            modelBuilder.Entity("Backend.Models.TestQuestion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("QuestionId")
                        .HasColumnType("bigint")
                        .HasColumnName("question_id");

                    b.Property<long?>("SequenceOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_order");

                    b.Property<long?>("TestId")
                        .HasColumnType("bigint")
                        .HasColumnName("test_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "QuestionId" }, "question_id")
                        .HasDatabaseName("question_id4");

                    b.HasIndex(new[] { "TestId" }, "test_id");

                    b.ToTable("test_questions", (string)null);
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Contact")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("contact");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Status")
                        .HasColumnType("enum('ACTIVE','INACTIVE','BLOCKED')")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Backend.Models.UserLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("LoginTime")
                        .HasColumnType("datetime")
                        .HasColumnName("login_time");

                    b.Property<DateTime?>("LogoutTime")
                        .HasColumnType("datetime")
                        .HasColumnName("logout_time");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "fk_user_logs_user");

                    b.ToTable("user_logs", (string)null);
                });

            modelBuilder.Entity("Backend.Models.UserRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("assigned_at");

                    b.Property<long?>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RoleId" }, "role_id");

                    b.HasIndex(new[] { "UserId" }, "user_id")
                        .HasDatabaseName("user_id8");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Backend.Models.AcademicInformation", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("AcademicInformations")
                        .HasForeignKey("UserId")
                        .HasConstraintName("academic_informations_ibfk_1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Alumnus", b =>
                {
                    b.HasOne("Backend.Models.Company", "Companies")
                        .WithMany("Alumni")
                        .HasForeignKey("CompaniesId")
                        .HasConstraintName("alumni_ibfk_1");

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("Alumni")
                        .HasForeignKey("UserId")
                        .HasConstraintName("alumni_ibfk_2");

                    b.Navigation("Companies");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Assessment", b =>
                {
                    b.HasOne("Backend.Models.User", "AssignedByNavigation")
                        .WithMany("AssessmentAssignedByNavigations")
                        .HasForeignKey("AssignedBy")
                        .HasConstraintName("fk_assessment_assigned_by");

                    b.HasOne("Backend.Models.User", "Student")
                        .WithMany("AssessmentStudents")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("fk_assessment_student");

                    b.HasOne("Backend.Models.Test", "Test")
                        .WithMany("Assessments")
                        .HasForeignKey("TestId")
                        .HasConstraintName("fk_assessment_test");

                    b.Navigation("AssignedByNavigation");

                    b.Navigation("Student");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Backend.Models.Framework", b =>
                {
                    b.HasOne("Backend.Models.Language", "Language")
                        .WithMany("Frameworks")
                        .HasForeignKey("LanguageId")
                        .HasConstraintName("frameworks_ibfk_2");

                    b.HasOne("Backend.Models.Layer", "Layer")
                        .WithMany("Frameworks")
                        .HasForeignKey("LayerId")
                        .HasConstraintName("frameworks_ibfk_1");

                    b.Navigation("Language");

                    b.Navigation("Layer");
                });

            modelBuilder.Entity("Backend.Models.FrameworkConcept", b =>
                {
                    b.HasOne("Backend.Models.Concept", "Concept")
                        .WithMany("FrameworkConcepts")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("framework_concepts_ibfk_2");

                    b.HasOne("Backend.Models.Framework", "Framework")
                        .WithMany("FrameworkConcepts")
                        .HasForeignKey("FrameworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("framework_concepts_ibfk_1");

                    b.Navigation("Concept");

                    b.Navigation("Framework");
                });

            modelBuilder.Entity("Backend.Models.HandsOnResult", b =>
                {
                    b.HasOne("Backend.Models.Question", "Question")
                        .WithMany("HandsOnResults")
                        .HasForeignKey("QuestionId")
                        .HasConstraintName("fk_question_results");

                    b.HasOne("Backend.Models.User", "Sme")
                        .WithMany("HandsOnResultSmes")
                        .HasForeignKey("SmeId")
                        .HasConstraintName("hands_on_results_ibfk_3");

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("HandsOnResultUsers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("hands_on_results_ibfk_1");

                    b.Navigation("Question");

                    b.Navigation("Sme");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.HandsOnSubmission", b =>
                {
                    b.HasOne("Backend.Models.Question", "Question")
                        .WithMany("HandsOnSubmissions")
                        .HasForeignKey("QuestionId")
                        .HasConstraintName("fk_question_submissions");

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("HandsOnSubmissions")
                        .HasForeignKey("UserId")
                        .HasConstraintName("hands_on_submissions_ibfk_2");

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Interview", b =>
                {
                    b.HasOne("Backend.Models.JobApplication", "Application")
                        .WithMany("Interviews")
                        .HasForeignKey("ApplicationId")
                        .HasConstraintName("fk_interview_application");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("Backend.Models.JobApplication", b =>
                {
                    b.HasOne("Backend.Models.JobDescription", "Job")
                        .WithMany("JobApplications")
                        .HasForeignKey("JobId")
                        .HasConstraintName("fk_app_job");

                    b.HasOne("Backend.Models.User", "Student")
                        .WithMany("JobApplications")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("fk_app_student");

                    b.Navigation("Job");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Backend.Models.JobDescription", b =>
                {
                    b.HasOne("Backend.Models.User", "Employer")
                        .WithMany("JobDescriptions")
                        .HasForeignKey("EmployerId")
                        .HasConstraintName("fk_job_employer");

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("Backend.Models.Language", b =>
                {
                    b.HasOne("Backend.Models.Runtime", "Runtime")
                        .WithMany("Languages")
                        .HasForeignKey("RuntimeId")
                        .HasConstraintName("languages_ibfk_1");

                    b.Navigation("Runtime");
                });

            modelBuilder.Entity("Backend.Models.LearningPath", b =>
                {
                    b.HasOne("Backend.Models.User", "Mentor")
                        .WithMany("LearningPaths")
                        .HasForeignKey("MentorId")
                        .HasConstraintName("fk_learningpath_mentor");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("Backend.Models.LearningPathProgress", b =>
                {
                    b.HasOne("Backend.Models.LearningPath", "LearningPath")
                        .WithMany("LearningPathProgresses")
                        .HasForeignKey("LearningPathId")
                        .HasConstraintName("fk_progress_path");

                    b.HasOne("Backend.Models.User", "Student")
                        .WithMany("LearningPathProgresses")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("fk_progress_student");

                    b.Navigation("LearningPath");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Backend.Models.LearningResource", b =>
                {
                    b.HasOne("Backend.Models.User", "UploadedByNavigation")
                        .WithMany("LearningResources")
                        .HasForeignKey("UploadedBy")
                        .HasConstraintName("fk_resource_user");

                    b.Navigation("UploadedByNavigation");
                });

            modelBuilder.Entity("Backend.Models.McqOption", b =>
                {
                    b.HasOne("Backend.Models.Question", "Question")
                        .WithMany("McqOptions")
                        .HasForeignKey("QuestionId")
                        .HasConstraintName("mcq_options_ibfk_1");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Backend.Models.MentorAppointment", b =>
                {
                    b.HasOne("Backend.Models.User", "Mentor")
                        .WithMany("MentorAppointmentMentors")
                        .HasForeignKey("MentorId")
                        .HasConstraintName("fk_appointment_mentor");

                    b.HasOne("Backend.Models.User", "Student")
                        .WithMany("MentorAppointmentStudents")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("fk_appointment_student");

                    b.Navigation("Mentor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Backend.Models.MentorCounseling", b =>
                {
                    b.HasOne("Backend.Models.User", "Mentee")
                        .WithMany("MentorCounselingMentees")
                        .HasForeignKey("MenteeId")
                        .HasConstraintName("fk_counseling_mentee");

                    b.HasOne("Backend.Models.User", "Mentor")
                        .WithMany("MentorCounselingMentors")
                        .HasForeignKey("MentorId")
                        .HasConstraintName("fk_counseling_mentor");

                    b.Navigation("Mentee");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("Backend.Models.MentorFeedback", b =>
                {
                    b.HasOne("Backend.Models.User", "Mentor")
                        .WithMany("MentorFeedbackMentors")
                        .HasForeignKey("MentorId")
                        .HasConstraintName("fk_feedback_mentor");

                    b.HasOne("Backend.Models.User", "Student")
                        .WithMany("MentorFeedbackStudents")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("fk_feedback_student");

                    b.Navigation("Mentor");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Backend.Models.MentorMentee", b =>
                {
                    b.HasOne("Backend.Models.User", "Mentee")
                        .WithMany("MentorMenteeMentees")
                        .HasForeignKey("MenteeId")
                        .HasConstraintName("mentor_mentees_ibfk_2");

                    b.HasOne("Backend.Models.User", "Mentor")
                        .WithMany("MentorMenteeMentors")
                        .HasForeignKey("MentorId")
                        .HasConstraintName("mentor_mentees_ibfk_1");

                    b.Navigation("Mentee");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("Backend.Models.Notification", b =>
                {
                    b.HasOne("Backend.Models.NotificationCategory", "NotificationCategories")
                        .WithMany("Notifications")
                        .HasForeignKey("NotificationCategoriesId")
                        .HasConstraintName("fk_notification_category");

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_notification_user");

                    b.Navigation("NotificationCategories");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.OralAssessment", b =>
                {
                    b.HasOne("Backend.Models.Concept", "Concept")
                        .WithMany("OralAssessments")
                        .HasForeignKey("ConceptId")
                        .HasConstraintName("fk_oa_concept");

                    b.HasOne("Backend.Models.User", "Sme")
                        .WithMany("OralAssessmentSmes")
                        .HasForeignKey("SmeId")
                        .HasConstraintName("fk_oa_sme");

                    b.HasOne("Backend.Models.User", "Student")
                        .WithMany("OralAssessmentStudents")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("fk_oa_student");

                    b.Navigation("Concept");

                    b.Navigation("Sme");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Backend.Models.OralQuestionAnswer", b =>
                {
                    b.HasOne("Backend.Models.User", "Sme")
                        .WithMany("OralQuestionAnswerSmes")
                        .HasForeignKey("SmeId")
                        .HasConstraintName("fk_oqa_sme");

                    b.HasOne("Backend.Models.User", "Student")
                        .WithMany("OralQuestionAnswerStudents")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("fk_oqa_student");

                    b.Navigation("Sme");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Backend.Models.PerformanceSnapshot", b =>
                {
                    b.HasOne("Backend.Models.User", "Student")
                        .WithMany("PerformanceSnapshots")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("fk_snapshot_student");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Backend.Models.PersonalInformation", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("PersonalInformations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("personal_informations_ibfk_1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.ProblemStatementAnswer", b =>
                {
                    b.HasOne("Backend.Models.Question", "Question")
                        .WithMany("ProblemStatementAnswers")
                        .HasForeignKey("QuestionId")
                        .HasConstraintName("fk_psa_question");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Backend.Models.ProfessionalInformation", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("ProfessionalInformations")
                        .HasForeignKey("UserId")
                        .HasConstraintName("professional_informations_ibfk_1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Project", b =>
                {
                    b.HasOne("Backend.Models.User", "Mentor")
                        .WithMany("Projects")
                        .HasForeignKey("MentorId")
                        .HasConstraintName("fk_project_mentor");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("Backend.Models.ProjectMember", b =>
                {
                    b.HasOne("Backend.Models.Project", "Project")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("fk_pm_project");

                    b.HasOne("Backend.Models.User", "Student")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("fk_pm_student");

                    b.Navigation("Project");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Backend.Models.QuestionFrameworkConcept", b =>
                {
                    b.HasOne("Backend.Models.FrameworkConcept", "FrameworkConcepts")
                        .WithMany("QuestionFrameworkConcepts")
                        .HasForeignKey("FrameworkConceptsId")
                        .HasConstraintName("question_framework_concepts_ibfk_2");

                    b.HasOne("Backend.Models.Question", "Question")
                        .WithMany("QuestionFrameworkConcepts")
                        .HasForeignKey("QuestionId")
                        .HasConstraintName("question_framework_concepts_ibfk_1");

                    b.Navigation("FrameworkConcepts");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Backend.Models.Referral", b =>
                {
                    b.HasOne("Backend.Models.Alumnus", "Alumni")
                        .WithMany("Referrals")
                        .HasForeignKey("AlumniId")
                        .HasConstraintName("referrals_ibfk_3");

                    b.HasOne("Backend.Models.Company", "Companies")
                        .WithMany("Referrals")
                        .HasForeignKey("CompaniesId")
                        .HasConstraintName("referrals_ibfk_1");

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("Referrals")
                        .HasForeignKey("UserId")
                        .HasConstraintName("referrals_ibfk_2");

                    b.Navigation("Alumni");

                    b.Navigation("Companies");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.ShortlistedCandidate", b =>
                {
                    b.HasOne("Backend.Models.JobDescription", "Job")
                        .WithMany("ShortlistedCandidates")
                        .HasForeignKey("JobId")
                        .HasConstraintName("fk_sc_job");

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("ShortlistedCandidates")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_sc_user");

                    b.Navigation("Job");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.SmeRuntime", b =>
                {
                    b.HasOne("Backend.Models.Runtime", "Runtime")
                        .WithMany("SmeRuntimes")
                        .HasForeignKey("RuntimeId")
                        .HasConstraintName("sme_runtimes_ibfk_2");

                    b.Navigation("Runtime");
                });

            modelBuilder.Entity("Backend.Models.StudentAssessmentResult", b =>
                {
                    b.HasOne("Backend.Models.Assessment", "Assessment")
                        .WithMany("StudentAssessmentResults")
                        .HasForeignKey("AssessmentId")
                        .HasConstraintName("fk_result_assessment");

                    b.HasOne("Backend.Models.User", "Student")
                        .WithMany("StudentAssessmentResults")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("fk_result_student");

                    b.Navigation("Assessment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Backend.Models.StudentConceptProgress", b =>
                {
                    b.HasOne("Backend.Models.Concept", "Concept")
                        .WithMany("StudentConceptProgresses")
                        .HasForeignKey("ConceptId")
                        .HasConstraintName("fk_scp_concept");

                    b.HasOne("Backend.Models.User", "Student")
                        .WithMany("StudentConceptProgresses")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("fk_scp_student");

                    b.Navigation("Concept");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Backend.Models.Test", b =>
                {
                    b.HasOne("Backend.Models.SmeRuntime", "SmeRuntime")
                        .WithMany("Tests")
                        .HasForeignKey("SmeRuntimeId")
                        .HasConstraintName("fk_sme_runtime");

                    b.Navigation("SmeRuntime");
                });

            modelBuilder.Entity("Backend.Models.TestQuestion", b =>
                {
                    b.HasOne("Backend.Models.Question", "Question")
                        .WithMany("TestQuestions")
                        .HasForeignKey("QuestionId")
                        .HasConstraintName("test_questions_ibfk_2");

                    b.HasOne("Backend.Models.Test", "Test")
                        .WithMany("TestQuestions")
                        .HasForeignKey("TestId")
                        .HasConstraintName("test_questions_ibfk_1");

                    b.Navigation("Question");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Backend.Models.UserLog", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("UserLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_user_logs_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.UserRole", b =>
                {
                    b.HasOne("Backend.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("user_roles_ibfk_2");

                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .HasConstraintName("user_roles_ibfk_1");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Alumnus", b =>
                {
                    b.Navigation("Referrals");
                });

            modelBuilder.Entity("Backend.Models.Assessment", b =>
                {
                    b.Navigation("StudentAssessmentResults");
                });

            modelBuilder.Entity("Backend.Models.Company", b =>
                {
                    b.Navigation("Alumni");

                    b.Navigation("Referrals");
                });

            modelBuilder.Entity("Backend.Models.Concept", b =>
                {
                    b.Navigation("FrameworkConcepts");

                    b.Navigation("OralAssessments");

                    b.Navigation("StudentConceptProgresses");
                });

            modelBuilder.Entity("Backend.Models.Framework", b =>
                {
                    b.Navigation("FrameworkConcepts");
                });

            modelBuilder.Entity("Backend.Models.FrameworkConcept", b =>
                {
                    b.Navigation("QuestionFrameworkConcepts");
                });

            modelBuilder.Entity("Backend.Models.JobApplication", b =>
                {
                    b.Navigation("Interviews");
                });

            modelBuilder.Entity("Backend.Models.JobDescription", b =>
                {
                    b.Navigation("JobApplications");

                    b.Navigation("ShortlistedCandidates");
                });

            modelBuilder.Entity("Backend.Models.Language", b =>
                {
                    b.Navigation("Frameworks");
                });

            modelBuilder.Entity("Backend.Models.Layer", b =>
                {
                    b.Navigation("Frameworks");
                });

            modelBuilder.Entity("Backend.Models.LearningPath", b =>
                {
                    b.Navigation("LearningPathProgresses");
                });

            modelBuilder.Entity("Backend.Models.NotificationCategory", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Backend.Models.Project", b =>
                {
                    b.Navigation("ProjectMembers");
                });

            modelBuilder.Entity("Backend.Models.Question", b =>
                {
                    b.Navigation("HandsOnResults");

                    b.Navigation("HandsOnSubmissions");

                    b.Navigation("McqOptions");

                    b.Navigation("ProblemStatementAnswers");

                    b.Navigation("QuestionFrameworkConcepts");

                    b.Navigation("TestQuestions");
                });

            modelBuilder.Entity("Backend.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Backend.Models.Runtime", b =>
                {
                    b.Navigation("Languages");

                    b.Navigation("SmeRuntimes");
                });

            modelBuilder.Entity("Backend.Models.SmeRuntime", b =>
                {
                    b.Navigation("Tests");
                });

            modelBuilder.Entity("Backend.Models.Test", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("TestQuestions");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Navigation("AcademicInformations");

                    b.Navigation("Alumni");

                    b.Navigation("AssessmentAssignedByNavigations");

                    b.Navigation("AssessmentStudents");

                    b.Navigation("HandsOnResultSmes");

                    b.Navigation("HandsOnResultUsers");

                    b.Navigation("HandsOnSubmissions");

                    b.Navigation("JobApplications");

                    b.Navigation("JobDescriptions");

                    b.Navigation("LearningPathProgresses");

                    b.Navigation("LearningPaths");

                    b.Navigation("LearningResources");

                    b.Navigation("MentorAppointmentMentors");

                    b.Navigation("MentorAppointmentStudents");

                    b.Navigation("MentorCounselingMentees");

                    b.Navigation("MentorCounselingMentors");

                    b.Navigation("MentorFeedbackMentors");

                    b.Navigation("MentorFeedbackStudents");

                    b.Navigation("MentorMenteeMentees");

                    b.Navigation("MentorMenteeMentors");

                    b.Navigation("Notifications");

                    b.Navigation("OralAssessmentSmes");

                    b.Navigation("OralAssessmentStudents");

                    b.Navigation("OralQuestionAnswerSmes");

                    b.Navigation("OralQuestionAnswerStudents");

                    b.Navigation("PerformanceSnapshots");

                    b.Navigation("PersonalInformations");

                    b.Navigation("ProfessionalInformations");

                    b.Navigation("ProjectMembers");

                    b.Navigation("Projects");

                    b.Navigation("Referrals");

                    b.Navigation("ShortlistedCandidates");

                    b.Navigation("StudentAssessmentResults");

                    b.Navigation("StudentConceptProgresses");

                    b.Navigation("UserLogs");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
