spring.application.name=Backend
server.port=9595

# External API (the other Maven/Spring service) used by `ExternalAPI`
external.api.base-url=http://localhost:8585
external.api.runtime-path=api/runtimes
external.api.language-path=api/languages/runtime
external.api.layer-path=api/layers
external.api.framework-path=api/frameworks/languages

spring.datasource.url=jdbc:mysql://192.168.1.149:3306/tflcomentor_db
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect